### ISSUE TITLE
organization id containing 18 digits changing last 2 to 00

### ISSUE THREAD

**Issue by jcsjacobs** [tejashah88/node-meraki-dashboard#4]
I have organisation id's that are 18 digits long (example: 565637804281575100)
the first 16 are ok but the last 2 have changed to 00.

I think the bigint is not supported so the integer is modified and therefor no loner working

**Comment by tejashah88** [comment]
It seems like numerical values are processed before the request happens. Does passing a string of the same org id work?

**Comment by jcsjacobs** [comment]
well I already get them resulted wrong when I just request the different organisations with the dashboard.organizations.list().
when I request the organizations with postman and then pass the correct id for the admins it works.

**Comment by tejashah88** [comment]
I checked the docs and it seems like the org number is returned as a number, which means that the API itself is truncating the org id before sending the response to you. You should file a bug report to Meraki about this since this library is just a wrapper to the API.

**Comment by jcsjacobs** [comment]
is there no solution in interpreting the numbers as big integers as the results come back?

**Comment by tejashah88** [comment]
I can look into adding bigint for handling org ids. I'm actually in the process of adding tests so I'll look into this matter a bit later. But if the API itself is returning a different org id, then I can't do much.

**Comment by jcsjacobs** [comment]
I understand but when I run it with postman I get the correct numbers..
so the return should be the same? right?
thank you for looking in to this.

**Comment by tejashah88** [comment]
My bad! I didn't see that the first time. I'll add some tests to fix this regression so stay tuned! In the meantime, you could probably wrap the org id in a BigInt and converting that to a string.

**Comment by tejashah88** [comment]
@jcsjacobs I just released v1.2.0, which should address this issue. Let me know if it works or not :)

**Comment by jcsjacobs** [comment]
Sorry for the somewhat late comment but I've tested it and now it is working perfectly.
thanks for the quick change and response
