### ISSUE TITLE
What does "slightly opinionated" mean?

### ISSUE THREAD

**Issue by pdlove** [tejashah88/node-meraki-dashboard#6]

**Comment by tejashah88** [comment]
@pdlove At the time of initially writing the module, its intention was to provide a modern node client library for the Meraki Dashboard API with a few optimizations such as consistent error logging and first class promise support. Those optimizations are my opinion(s) as to how a proper node.js client library, although in retrospect, the phrase isn't really necessary.

**Comment by pdlove** [comment]
Just curious! Thanks for the work on this.
