### ISSUE TITLE
index.js missing

### ISSUE THREAD

**Issue by lal12** [tejashah88/node-meraki-dashboard#7]
I tried to use the npm package, which does not work as described in the README. The problem is that there is no index.js in the main folder instead it is in the src folder. However node won't find it there, you have to write `require("node-meraki-dashboard/src/index.js")` to get it working. So you have to add a index.js into the main folder which exports the one in the src folder or change the "main" field in the package.json to "src/index.js".

**Comment by tejashah88** [comment]
@lal12 Thanks for catching that! I completely forgot to change it while refactoring the library.

**Comment by tejashah88** [comment]
It has been patched in v2.1.1
