### ISSUE TITLE
2 New Group Policy API endpoints

### ISSUE THREAD

**Issue by pocc** [tejashah88/node-meraki-dashboard#8]
# Missing API endpoint
* DELETE /networks/{networkId}/groupPolicies/{groupPolicyId}
> [link](https://dashboard.meraki.com/api_docs#delete-a-group-policy)

---

Congrats by the way. This is the best Meraki API Client that I've come across, based on implemented API calls and code readability.

**Comment by tejashah88** [comment]
@pocc So the first endpoint is already implemented under `dashboard.group_policies.list` ([docs](https://github.com/tejashah88/node-meraki-dashboard/blob/master/DOCUMENTATION.md#group-policies)), but the second one is new. Thank you!

**Comment by pocc** [comment]
Ah my bad. Edited issue.

**Comment by tejashah88** [comment]
Closing with the release of v3.0.0!
